services:
  backend-express:
    container_name: tickitzbe-zg
    image: zikrigusli/tickitzapi:3
    ports:
      - "3002:3001"
    environment:
      - DB_PORT=5432
    networks:
      - gonet

networks:
  gonet:
    name: coba
    external: true
# docker compose up -d
# docker compose down
