services:
  backend:
    container_name: "tickitzbe"
    # image buatan
    image: zikrigusli/tickitzapi:2
    ports:
      - "3002:3001"
    # .env akan ditimpa dengan envirotment dibawah
    environment:
      - DB_HOST=postgres
    networks:
      - gonet

networks:
  gonet:
    name: "coba"
    # eksternal true menandakan bahwa network sudah ada, tidak perlu buat lagi
    external: true
# docker compose up -d
# docker compose down
